# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:47
from __future__ import unicode_literals

import apps.core.utils.models
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=apps.core.utils.models.upload_to)),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30)),
                ('mother_tongue', models.BooleanField(default=False)),
                ('understanding_listening', models.CharField(choices=[(b'A1', b'A1 - Basic user'), (b'A2', b'A2 - Basic user'), (b'B1', b'B1 - Independent user'), (b'B2', b'B2 - Independent user'), (b'C1', b'C1 - Proficient user'), (b'C2', b'C2 - Proficient user')], max_length=2)),
                ('understanding_reading', models.CharField(choices=[(b'A1', b'A1 - Basic user'), (b'A2', b'A2 - Basic user'), (b'B1', b'B1 - Independent user'), (b'B2', b'B2 - Independent user'), (b'C1', b'C1 - Proficient user'), (b'C2', b'C2 - Proficient user')], max_length=2)),
                ('speaking_interaction', models.CharField(choices=[(b'A1', b'A1 - Basic user'), (b'A2', b'A2 - Basic user'), (b'B1', b'B1 - Independent user'), (b'B2', b'B2 - Independent user'), (b'C1', b'C1 - Proficient user'), (b'C2', b'C2 - Proficient user')], max_length=2)),
                ('speaking_production', models.CharField(choices=[(b'A1', b'A1 - Basic user'), (b'A2', b'A2 - Basic user'), (b'B1', b'B1 - Independent user'), (b'B2', b'B2 - Independent user'), (b'C1', b'C1 - Proficient user'), (b'C2', b'C2 - Proficient user')], max_length=2)),
                ('writing', models.CharField(choices=[(b'A1', b'A1 - Basic user'), (b'A2', b'A2 - Basic user'), (b'B1', b'B1 - Independent user'), (b'B2', b'B2 - Independent user'), (b'C1', b'C1 - Proficient user'), (b'C2', b'C2 - Proficient user')], max_length=2)),
            ],
            options={
                'ordering': ['-mother_tongue', 'language'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('short_description', models.CharField(blank=True, max_length=250, null=True)),
                ('about', tinymce.models.HTMLField(blank=True, null=True)),
                ('footer_text', tinymce.models.HTMLField(blank=True, null=True)),
                ('address', tinymce.models.HTMLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('skype', models.CharField(blank=True, max_length=30, null=True)),
                ('hobbies', tinymce.models.HTMLField(blank=True, null=True)),
                ('other_skills', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': 'id',
                'verbose_name_plural': 'Personal Information',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Work Experience',
            },
        ),
        migrations.CreateModel(
            name='WorkExperiencePortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=apps.core.utils.models.upload_to)),
                ('key_technologies', tinymce.models.HTMLField(blank=True, null=True)),
                ('main_activities', tinymce.models.HTMLField(blank=True, null=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='curriculum.WorkExperience')),
            ],
        ),
    ]
