# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identification', models.CharField(help_text=b'Company and reason', max_length=150)),
                ('hash', models.CharField(db_index=True, max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('header', tinymce.models.HTMLField(blank=True, null=True)),
                ('footer', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
