# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationemail',
            name='footer',
        ),
        migrations.AddField(
            model_name='presentationemail',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
